services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    image: student-performance-prediction-model:latest
    container_name: student_performance_api

    ports:
      - "8006:8006"

    environment:
      PYTHONUNBUFFERED: "1"
      PORT: "8006"

    restart: always