services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: student-performance-prediction-model:latest
    container_name: student_performance_api
    ports:
      - "8000:8000"
    volumes:
      # Mount the current directory to enable live reloading during development
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    # Overrides default entrypoint to run startup tasks
    entrypoint: ["/bin/bash", "/app/scripts/entrypoint.sh"]
    # Overrides Dockerfile CMD to include --reload for development
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: always
